framework:
    rate_limiter:
        # Define a rate limiter for login attempts
        login:
            policy: 'fixed_window'
            limit: 3
            interval: '3 minutes'
        # Define a rate limiter for registration attempts
        registration:
            policy: 'fixed_window'
            limit: 3
            interval: '15 minutes'
